# Generated by Django 4.1.4 on 2022-12-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_information',
            old_name='gender',
            new_name='grade',
        ),
    ]
